package com.sri.yices;
/*
 * !!!!EDITING IS FUTILE!!!!
 *
 * Version.java is autogenerated by the any build process.
 *
 * See Version.template.
 *
 *
 */

public final class Version {


    public static final String versionString = "1.0.1";
    public static final String buildDate = "April 3 2020";
    
    
    public static void main(String[] args){
	StringBuilder sb = new StringBuilder();
	sb.append("\nYices Java Bindings Version ").append(versionString);
	sb.append("\nBuild date: ").append(buildDate);
	sb.append("\nusing Yices dynamic library version ").append(Yices.version());
	sb.append("\nBuilt for ").append(Yices.buildArch());
	sb.append("\nBuild mode: ").append(Yices.buildMode());
	sb.append("\nBuild date: ").append(Yices.buildDate());
	sb.append("\nMCSat supported: ").append(Yices.hasMcsat());
	sb.append("\nThread safe: ").append(Yices.isThreadSafe());
	sb.append("\n");
	System.err.println(sb);
    }


    
}
